stages:
  - build
  - push
  - deploy

variables:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 922805825674.dkr.ecr.us-east-1.amazonaws.com
  CLUSTER_NAME: tissue-cluster
  NAMESPACE: test
  RELEASE_NAME: msa-services
  CHART_PATH: msa-chart
  TAG: latest

before_script:
  - apk add --no-cache curl python3 py3-pip docker helm
  - pip3 install awscli
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region $AWS_REGION
  - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

build:
  stage: build
  script:
    - docker build -t $ECR_REGISTRY/auth_service:$TAG ./services/auth-service
    - docker build -t $ECR_REGISTRY/report_service:$TAG ./services/report-service
    - docker build -t $ECR_REGISTRY/chatbot_service:$TAG ./services/chatbot-service
    - docker build -t $ECR_REGISTRY/youtube_service:$TAG ./services/youtube-service

push:
  stage: push
  script:
    - docker push $ECR_REGISTRY/auth_service:$TAG
    - docker push $ECR_REGISTRY/report_service:$TAG
    - docker push $ECR_REGISTRY/chatbot_service:$TAG
    - docker push $ECR_REGISTRY/youtube_service:$TAG

deploy:
  stage: deploy
  script:
    - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
    - helm upgrade --install $RELEASE_NAME $CHART_PATH -n $NAMESPACE --create-namespace \
        --set services[0].image=$ECR_REGISTRY/auth_service:$TAG \
        --set services[1].image=$ECR_REGISTRY/report_service:$TAG \
        --set services[2].image=$ECR_REGISTRY/chatbot_service:$TAG \
        --set services[3].image=$ECR_REGISTRY/youtube_service:$TAG

