image: docker:20.10.16

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: "" 
  AWS_REGION: us-east-1
  ECR_REGISTRY: 922805825674.dkr.ecr.us-east-1.amazonaws.com
  CLUSTER_NAME: tissue-cluster
  NAMESPACE: test
  RELEASE_NAME: msa-services
  CHART_PATH: msa-chart
  TAG: latest

stages:
  - build
  - push
  - deploy

before_script:
  - apk add --no-cache bash curl python3 py3-pip openssl
  - pip3 install --upgrade pip awscli
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
  - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
  - aws configure set default.region "$AWS_REGION"
  - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"


build:
  stage: build
  script:
    - docker build -t $ECR_REGISTRY/auth_service:$TAG ./app/auth_service
    - docker build -t $ECR_REGISTRY/report_service:$TAG ./app/report_service
    - docker build -t $ECR_REGISTRY/chatbot_service:$TAG ./app/chatbot_service
    - docker build -t $ECR_REGISTRY/youtube_service:$TAG ./app/youtube_service

push:
  stage: push
  script:
    - docker push $ECR_REGISTRY/auth_service:$TAG
    - docker push $ECR_REGISTRY/report_service:$TAG
    - docker push $ECR_REGISTRY/chatbot_service:$TAG
    - docker push $ECR_REGISTRY/youtube_service:$TAG

deploy:
  stage: deploy
  script:
    - aws eks update-kubeconfig --region "$AWS_REGION" --name "$CLUSTER_NAME"
    - helm upgrade --install "$RELEASE_NAME" "$CHART_PATH" -n "$NAMESPACE" --create-namespace \
        --set services[0].image=$ECR_REGISTRY/auth_service:$TAG \
        --set services[1].image=$ECR_REGISTRY/report_service:$TAG \
        --set services[2].image=$ECR_REGISTRY/chatbot_service:$TAG \
        --set services[3].image=$ECR_REGISTRY/youtube_service:$TAG
