{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          ports:
            - containerPort: {{ .port }}
          command: ["uvicorn"]
          args:
            - "main:app"
            - "--host"
            - "0.0.0.0"
            - "--port={{ .port }}"

          env:
            {{- if eq .name "auth-service" }}
            - name: COGNITO_CLIENT_ID
              value: "{{ .cognitoClientId }}"
            - name: COGNITO_CLIENT_SECRET
              value: "{{ .cognitoClientSecret }}"
            - name: AWS_REGION
              value: "{{ .awsRegion }}"
            {{- end }}
---
{{- end }}
