apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msa-ingress
  namespace: test
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/load-balancer-name: msa-alb
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /auth
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /report
            pathType: ImplementationSpecific
            backend:
              service:
                name: report-service
                port:
                  number: 80
          - path: /analyze
            pathType: ImplementationSpecific
            backend:
              service:
                name: report-service
                port:
                  number: 80
          - path: /youtube
            pathType: ImplementationSpecific
            backend:
              service:
                name: youtube-service
                port:
                  number: 80
          - path: /search
            pathType: ImplementationSpecific
            backend:
              service:
                name: youtube-service
                port:
                  number: 80
          - path: /chatbot
            pathType: ImplementationSpecific
            backend:
              service:
                name: chatbot-service
                port:
                  number: 80
