apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msa-ingress
  namespace: test
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /auth
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /report
            pathType: ImplementationSpecific
            backend:
              service:
                name: report-service
                port:
                  number: 80
          - path: /analyze
            pathType: ImplementationSpecific
            backend:
              service:
                name: report-service
                port:
                  number: 80
          - path: /youtube
            pathType: ImplementationSpecific
            backend:
              service:
                name: youtube-service
                port:
                  number: 80
          - path: /search
            pathType: ImplementationSpecific
            backend:
              service:
                name: youtube-service
                port:
                  number: 80
          - path: /chatbot
            pathType: ImplementationSpecific
            backend:
              service:
                name: chatbot-service
                port:
                  number: 80
