{{- range .Values.services }}
{{- if not .name }}
{{- fail "? Error: One of the services is missing a 'name' field in values.yaml" }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - port: 80
      targetPort: {{ .port }}
---
{{- end }}
