name: CI/CD to EKS via ECR

on:
  push:
    branches:
      - v3

env:
  AWS_REGION: us-west-2
  ECR_REGISTRY: 922805825674.dkr.ecr.us-west-2.amazonaws.com
  CLUSTER_NAME: tissue-cluster
  NAMESPACE: test
  RELEASE_NAME: msa
  CHART_PATH: msa-chart
  TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Docker images
        run: |
          docker build -t $ECR_REGISTRY/auth_service:$TAG ./app/auth_service
          docker build -t $ECR_REGISTRY/report_service:$TAG ./app/report_service
          docker build -t $ECR_REGISTRY/chatbot_service:$TAG ./app/chatbot_service
          docker build -t $ECR_REGISTRY/youtube_service:$TAG ./app/youtube_service

      - name: Push Docker images to ECR
        run: |
          docker push $ECR_REGISTRY/auth_service:$TAG
          docker push $ECR_REGISTRY/report_service:$TAG
          docker push $ECR_REGISTRY/chatbot_service:$TAG
          docker push $ECR_REGISTRY/youtube_service:$TAG

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

